ALTER TABLE audit_events DROP CONSTRAINT audit_events_event_type_check;

ALTER TABLE audit_events
  ADD CONSTRAINT audit_events_event_type_check CHECK (event_type IN (
    'USER_CREATED', 'USER_ROLE_CHANGED', 'USER_ACTIVATED',
    'USER_DEACTIVATED', 'USER_PASSWORD_RESET',
    'STAFF_PROFILE_UPDATED', 'STAFF_MANAGER_CHANGED',
    'CUSTOMER_CREATED', 'CUSTOMER_FIELDS_UPDATED',
    'CUSTOMER_ASSIGNEE_CHANGED', 'CUSTOMER_ACTIVATED',
    'CUSTOMER_DEACTIVATED', 'CONTACT_CREATED',
    'CONTACT_FIELDS_UPDATED', 'CONTACT_MADE_PRIMARY',
    'CONTACT_ACTIVATED', 'CONTACT_DEACTIVATED',
    'PRODUCT_CREATED', 'PRODUCT_FIELDS_UPDATED',
    'PRODUCT_ACTIVATED', 'PRODUCT_DEACTIVATED',
    'CUSTOMER_DELETED', 'PRODUCT_DELETED'
  ));
